### ISSUE TITLE
Message Unauthorised during CanvasDataDL_Tables_Latest.js

### ISSUE THREAD

**Issue by leahy268** [EMU-CFE/CanvasDataViewer#23]
Hi,

So I have downloaded CDV and installed it according to instructions.  When I run it everything works ok until this point:

  'bigint',
  "Id of this account's grand parent account.  This field will be NULL for the root account and all subaccounts at level 1.",
  'grandparent_account_id',
  'Name of the root account associated with this account.',
  'root_account',
  'varchar',
  ... 5285 more items
]
undefined
undefined
undefined
NULL
C:\Program Files\nodejs>node CanvasDataDL_Tables_Latest.js 
(node:4104) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
undefined:1
Unauthorized
^
NULL
SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\CanvasDataAuth_Tables.js:88:27)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
NULL

I can see that it seems to get the schema ok but when it starts to download the tables it doesn't work.  I have regenerated my secret and key and I have full admin permissions in the data portal.  

Thanks

**Comment by Terminal-IR** [comment]
Hello there,
I don't know if EMU is supporting this package anymore - see issue thread #20.

I'm in the initial testing phase of this package myself but have not run into this problem.  Doing some digging online, I found this which may help: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

Looking at the code in CanvasDataAuth_Schema.cdconfig and CanvasDataAuth_Tables.cdconfig it appears that these are the only places where the `new buffer()` function is being used.  Here are some suggested changes.  Can you make them and see if it solves your problem?

In CanvasDataAuth_Schema.cdconfig 
Can you replace line 50: 
`var hmac = crypto.createHmac(HMAC_ALG, new Buffer(secret)) `
with 
`var hmac = crypto.createHmac(HMAC_ALG, Buffer.from(secret))` 

And in CanvasDataAuth_Tables.cdconfig
Can you replace line 51:
`var hmac = crypto.createHmac(HMAC_ALG, new Buffer(secret)) `
with
`var hmac = crypto.createHmac(HMAC_ALG, Buffer.from(secret))`

**Comment by bguimaraes** [comment]
I had the same problem as leahy268.
Following the steps that Terminal-IR suggested and now I have a new error ;(

--------------------------------------
  ... 5285 more items
]
undefined
undefined
undefined
NULL
C:\Program Files\nodejs>node CanvasDataDL_Tables_Latest.js 
undefined:1
Unauthorized
^
NULL
SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\CanvasDataAuth_Tables.js:87:27)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
NULL
--------------------------------------------

Does anyone know how to solve?

Thanks.
Bruno

**Comment by pauloburg** [comment]
Same problem here,
I replaced to Buffer.from in CanvasDataAuth_Tables.js, but not work.

Did anyone fix it?

**Comment by leahy268** [comment]
Hmm sorry I received the second comment but not the first.  As I had been called away to other projects I hadn't had time to come back to this one.  I will go in and make those changes and see what I can do.

**Comment by collaspj** [comment]
I'm currently experiencing exactly the same issue.    I've altered the 'buffer' statements, but they were just deprecation warnings.

It's the inability of the system to access the Canvas API that seems to be the issue, and I'm not sure why it isn't authorizing correctly.   I'm running the Stored Proc as an Administrator, and have the correct key and secret information.

I'm guessing there's something very simple about the API authorization that I'm missing.    Would be very grateful for any pointers.
